# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [example]

env:
  GGOOGLE_API_KEY: "AIzaSyDLVmqNDJXZ0JyhHR7sCmqY2BHYyPr1p6M"
  GOOGLE_TRANSLATIONS_KEY: "1BJNV4zqOzGnDbHVzfwdFQ6Eo2PW2GWTwMUiuZKzk8C0"

jobs:
  example:
    env:
      host: ${{ secrets.FTP_HOST }}
      user: ${{ secrets.FTP_USER }}
      pass: ${{ secrets.FTP_PASS }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"
      - run: npm ci
      - run: npm build:prod
      - run: node ./js/ftp.js "$host" "$user" "$pass"
